### ISSUE TITLE
Research on Github Release feature

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/template-gabarit#10]
Additional research on Github Release feature, as well as putting notes in the markdown file for Release Strategy.

See: https://github.com/gctools-outilsgc/template-gabarit/blob/master/Release_Strategy.md

**Comment by Phanoix** [comment]
docs: 
 - https://help.github.com/categories/releases/
 - can link to either a specific one or the latest release: https://help.github.com/articles/linking-to-releases/
 - can get download count though api
 - for automation: https://developer.github.com/v3/repos/releases/#create-a-release

also, work similarly in gitlab 
 - https://docs.gitlab.com/ee/workflow/releases.html

**Comment by MGoodberry** [comment]
@Phanoix Can we talk about what you find?
