### ISSUE TITLE
Templates for Release notes

### ISSUE THREAD

**Issue by s-duffey** [gctools-outilsgc/template-gabarit#11]
Research and creation of a Github template for Release notes. 

See: https://github.com/gctools-outilsgc/template-gabarit/blob/master/RELEASE%20NOTES_TEMPLATE.md

**Comment by MGoodberry** [comment]
Waiting for Dave to get back

**Comment by s-duffey** [comment]
@marianneaubrey15 can you confirm if we want a template for this? In our presentation it says release notes are based on Pull Requests and use four headers: additions, deletions, changes, fixes. A template might not be necessary! Let me know what you think, if a template is overkill go ahead and close this card :)
